### ISSUE TITLE
Add basic support for multiple displays (mirroring only)

### ISSUE THREAD

**Issue by yesthisisjoe** [yesthisisjoe/Wallpaperer#7]

**Comment by justindhill** [comment]
Hey, downloaded your app from the app store and searched for it on GitHub to see if it was here. Looks great - this is the feature I need most! :)

**Comment by yesthisisjoe** [comment]
Thanks, glad you like it! You're not alone, a few people have told me they want multi-monitor support and I totally understand why. It's one of my priorities and I hope to have support for this out in 1 to 2 weeks.
